<a href="https://colab.research.google.com/github/sriramtumu2006/Data_Science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
arr3=np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]])
print(arr3)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8  9 10]
  [11 12 13]]]


In [ ]:
zeros=np.zeros((2,3))
print(zeros)
ones=np.ones((3,3))
print(ones)
ran_arr=np.random.random((2,3))
print(ran_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.81779795 0.01866988 0.56045359]
 [0.95153774 0.06784803 0.97034526]]


In [ ]:
iden=np.eye((3))
print(iden)
aran=np.arange(0,10,2)
print(aran)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape : ",arr.shape)
print("Size : ",arr.size)
print("dType : ",arr.dtype)
print("Dimensions : ",arr.ndim)

Shape :  (2, 3)
Size :  6
dType :  int64
Dimensions :  2


In [ ]:
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data)
print()
print("Shape : ",temp_data.shape)
print("Size : ",temp_data.size)
print("dType : ",temp_data.dtype)
print("Dimensions : ",temp_data.ndim)
gh3=np.array([[21,22,23]])
updated_temp_data=np.append(temp_data,gh3,axis=0)
sensor_error_flags=np.zeros((2,3))
greenhouse_identity=np.eye((3))
print(updated_temp_data)
print()
print(sensor_error_flags)
print()
print(greenhouse_identity)

[[22 25 20]
 [24 26 23]]

Shape :  (2, 3)
Size :  6
dType :  int64
Dimensions :  2
[[22 25 20]
 [24 26 23]
 [21 22 23]]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a[1,0])
print(a[0:1])

4
[[1 2 3]]


You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [ ]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print(shipments)
print()
print("Apples Shipped on wednesday : ",shipments[0,2])
print("Oranges Shipped on Sunday : ",shipments[1,6])
print("Mon-Fri : ",shipments[0:,0:5])
print("Sat & Sun : ",shipments[0:,5:])
print("Apples Shipped from Wednesday to Saturday : ",shipments[0,2:6])
shipments[0,5]=100
print(shipments)

[[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]

Apples Shipped on wednesday :  55
Oranges Shipped on Sunday :  75
Mon-Fri :  [[50 60 55 70 65]
 [40 45 50 60 55]]
Sat & Sun :  [[80 90]
 [70 75]]
Apples Shipped from Wednesday to Saturday :  [55 70 65 80]
[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("a + b =\n",a+b)
print("a * b =\n",a*b)
print("a * 2 =\n",a*2)
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
res=np.dot(mat1,mat2)
print("Dot product : ",res)

a + b =
 [5 7 9]
a * b =
 [ 4 10 18]
a * 2 =
 [2 4 6]
Dot product :  [[19 22]
 [43 50]]


1. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)

🔹 2. Exponential and Logarithmic ufuncs
(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1

🔹 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)

🔹 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)

🔹 5. Statistical ufuncs
(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)

🔹 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)

🔹 7. Comparison ufuncs
(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)

🔹 8. Bitwise ufuncs
(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)


In [ ]:
a=np.array([1,2,3])
b=2
print(a+b)
print(a)
print("exp : ",np.exp(a))
print("sqrt :",np.sqrt(a))
print("log :",np.log(a))
print("max : ",np.max(a))
print("sin : ",np.sin(a))
print("logical_xor : ",np.logical_xor(3<4,3>4))
print("trunc :",np.trunc(1.89))

[3 4 5]
[1 2 3]
exp :  [ 2.71828183  7.3890561  20.08553692]
sqrt : [1.         1.41421356 1.73205081]
log : [0.         0.69314718 1.09861229]
max :  3
sin :  [0.84147098 0.90929743 0.14112001]
logical_xor :  True
trunc : 1.0


You are a data engineer at a renewable-energy company that runs 3 solar farms.
Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.

In [ ]:
import numpy as np
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
production_all=np.array([farmA,farmB,farmC])
print(production_all)
print("Shape : ",production_all.shape)
print("Size : ",production_all.size)
print("dType : ",production_all.dtype)
print("Dimensions : ",production_all.ndim)
total_per_farm=np.sum(production_all,axis=(1,2))
print("total per farm : ",total_per_farm)
print("Mean : ",np.mean(production_all,axis=(1,2)))
print("Std : ",np.std(production_all,axis=(1,2)))
print("Var : ",np.var(production_all,axis=(1,2)))
hour_weights=np.array([0.5,1.0,0.75])
weighted_per_panel=np.dot(production_all,hour_weights)
print("weighted_per_panel : ",weighted_per_panel)
print("Broadcasting 0.5 to farm B",production_all[1]+0.5)
farm_means = production_all.mean(axis=(1, 2))
farm_stds = production_all.std(axis=(1, 2))
normalized = (production_all - farm_means) / farm_stds
print("Mean Per farm:\n", farm_means)
print("Std Per farm:\n", farm_stds)
print("\nNormalized production values:\n", normalized)
print("exp : ",np.exp(normalized))
print("expm1 : ",np.expm1(normalized))
print("log : ",np.log(np.clip(normalized, 1e-6, None)))
print("log10 : ",np.log10(np.clip(normalized, 1e-6, None)))
print("log2 : ",np.log2(np.clip(normalized, 1e-6, None)))
print("sin : ",np.sin(normalized))
print("cos : ",np.cos(normalized))
print("tan : ",np.tan(normalized))
print("arcsin : ",np.arcsin(np.clip(np.sin(normalized), -1, 1)))
print("arccos : ",np.arccos(np.clip(np.cos(normalized), -1, 1)))
print("degrees : ",np.degrees(normalized))
print("radians : ",np.radians(normalized))
print("round : ",np.round(normalized))
print("floor : ",np.floor(normalized))
print("ceil : ",np.ceil(normalized))
print("trunc : ",np.trunc(normalized))
high_output = production_all > 20
even_hour_mask=(production_all % 2 == 0)
print("logical_and : ",np.logical_and(high_output,even_hour_mask))
print("logical_or : ",np.logical_or(high_output,even_hour_mask))
print("logical_not : ",np.logical_not(high_output))
print("logical_xor : ",np.logical_xor(high_output, even_hour_mask))
print("greater_equal_mask = ",np.greater_equal(production_all, 15))
print("less_mask = ",np.less(production_all, 10))
alerts = np.array([
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]]
])
print("bit_and =", np.bitwise_and(alerts, (production_all > 10)))
print("bit_or  = ",np.bitwise_or(alerts, (production_all < 10)))
print("bit_not = ",np.invert(alerts))
print("add: ",np.add(high_output,5))
print("subtract: ",np.subtract(high_output,5))
print("multiply: ",np.multiply(high_output,5))
print("divide: ",np.divide(high_output,5))
print("power: ",np.power(high_output,5))
print("mod: ",np.mod(high_output,5))
print("aggregate sum of np.exp: ",np.sum(np.exp(normalized)))
print("aggregate mean of np.sin: ",np.mean(np.sin(normalized)))
panel_totals_per_farm = np.sum(production_all, axis=(1, 2))
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=0)
needs_maintenance1 = np.min(panel_totals_per_farm < 40, axis=0)
needs_maintenance2 = np.max(panel_totals_per_farm < 40, axis=0)
print("panel_totals_per_farm: ",panel_totals_per_farm)
print("needs_maintenance: ",needs_maintenance)
print("needs_maintenance1: ",needs_maintenance1)
print("needs_maintenance2: ",needs_maintenance2)
overall_total = production_all.sum()
peak_hour_value = np.max(production_all)
peak_farm_panel = np.unravel_index(np.argmax(production_all), production_all.shape)
average_per_panel = np.mean(production_all)
print("Overall total energy:", overall_total)
print("Peak hour value:", peak_hour_value)
print("Farm and panel with peak hour value:", peak_farm_panel)
print("Average per panel across all farms:", average_per_panel)

[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]
Shape :  (3, 4, 3)
Size :  36
dType :  int64
Dimensions :  3
total per farm :  [126 234 174]
Mean :  [10.5 19.5 14.5]
Std :  [1.97905701 1.97905701 1.97905701]
Var :  [3.91666667 3.91666667 3.91666667]
weighted_per_panel :  [[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]
Broadcasting 0.5 to farm B [[20.5 19.5 21.5]
 [18.5 20.5 19.5]
 [22.5 23.5 21.5]
 [17.5 18.5 16.5]]
Mean Per farm:
 [10.5 19.5 14.5]
Std Per farm:
 [1.97905701 1.97905701 1.97905701]

Normalized production values:
 [[[-0.25264558 -3.78968364 -1.76851903]
  [-0.75793673 -4.2949748  -2.27381019]
  [ 0.75793673 -3.28439249 -0.25264558]
  [-1.26322788 -6.31613941 -2.77910134]]

 [[ 4.80026595 -0.25264558  3.28439249]
  [ 3.78968364  0.25264558  2.27381019]
  [ 5.81084826  1.76851903  3.28439249]
  [ 3.28439249 -0.75793673  0.75793

In [ ]:
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print(reshaped)
a=np.array([1,2])
b=np.array([3,4])
print("Vertical Stack : ",np.vstack((a,b)))
print("Horizontal Stack : ",np.hstack((a,b)))
a=np.array([1,2,3,4,5,6])
print("splitting : ",np.split(a,3))

[[1 2 3]
 [4 5 6]]
Vertical Stack :  [[1 2]
 [3 4]]
Horizontal Stack :  [1 2 3 4]
splitting :  [array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr[arr>3])
indices=[0,1]
print(arr[indices])

[4 5]
[1 2]


In [ ]:
#copy,view,save,load
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
print("view : ",arr)
copy=arr.copy()
copy[0]=20
print("After copying")
print("arr :",arr)
print("copy :",copy)
np.save('array.npy',arr)
loaded_arr=np.load('array.npy')
print("loaded_arr : ",loaded_arr)

view :  [10  2  3]
After copying
arr : [10  2  3]
copy : [20  2  3]
loaded_arr :  [10  2  3]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.



In [ ]:
arr=np.arange(10,51)
arr1=np.random.random ((3,3))
print(arr1)
print("Shape : ",arr1.shape)
print("Size : ",arr1.size)
print("dType : ",arr1.dtype)
print("Dimensions : ",arr1.ndim)
arr=arr+5
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print("a*b =",a*b)
ar=np.arange(1,26)
ar=ar.reshape(5,5)
print("array = ",ar)
print("first row=",ar[0])
print("last column =",ar[:,4:])
print("Subarray : ",ar[:3,:2])
br=np.arange(10,101,10)
print(br)
print("Max : ",np.max(br))
print("Min : ",np.min(br))
print("Mean : ",np.mean(br))
print("Std : ",np.std(br))
c1=np.arange(1,13)
print(c1.reshape(3,4))
ones=np.ones((3,3))
print(ones+[1,2,3])
d1=np.random.randint(1,51,15)
print(d1)
print(d1[d1%5==0])
print("Dot Product : ",np.dot(a,b))
e=np.arange(1,17).reshape(4,4)
print(e[[0,1,2,3],[0,1,2,3]])

[[0.58331782 0.83817293 0.96129108]
 [0.83197145 0.66596334 0.15391828]
 [0.65755114 0.37446623 0.86317515]]
Shape :  (3, 3)
Size :  9
dType :  float64
Dimensions :  2
a*b = [[ 5 12]
 [21 32]]
array =  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
first row= [1 2 3 4 5]
last column = [[ 5]
 [10]
 [15]
 [20]
 [25]]
Subarray :  [[ 1  2]
 [ 6  7]
 [11 12]]
[ 10  20  30  40  50  60  70  80  90 100]
Max :  100
Min :  10
Mean :  55.0
Std :  28.722813232690143
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[10  3 31 45 28 36 25 49 35 28 23 44 50 22 19]
[10 45 25 35 50]
Dot Product :  [[19 22]
 [43 50]]
[ 1  6 11 16]
